### ISSUE TITLE
ARRAY_SLICE is not defined.

### ISSUE THREAD

**Issue by RezaErfani67** [getify/asynquence#103]
i use map function with this code with 2 reference asq.src.js , plugin.map.js... and error ocuured...

ASQ(function step1(done){
    setTimeout(function(){
        done( [1,2,3] );
    });
})
.map(function step2(item,done){
    setTimeout(function(){
        done( item * 2 );
    },100);
})
.val(function(arr){
    console.log(arr); // [2,4,6]
});

**Comment by getify** [comment]
You need to build the contrib file with the appropriate plugins (such as "map") bundled into it... you can't just use the plugin file directly. More info: https://github.com/getify/asynquence/tree/master/contrib#building-contrib-bundle

**Comment by RezaErfani67** [comment]
tanks.
i read your link
also i read below link
https://davidwalsh.name/asynquence-part-2#asynquence-is-much-more-and-growing

but it doesn't work...
actually i cant understand how to build (plugin.map.js)
can you please give me simpler tutorial?

**Comment by RezaErfani67** [comment]
yess...found the solution...
i should add (contrib.js) reference after the plugin added...

<script src='asq.src.js'></script>
<script src='plugin.map.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/asynquence-contrib/0.28.0/contrib.js'></script>

thanks mr Simpson :)

**Comment by getify** [comment]
Take out "plugin.map.js"... its contents are already included in "contrib.js".
