### ISSUE TITLE
How to extend an ASQ iterable sequence while it's running?

### ISSUE THREAD

**Issue by akixxx1982** [getify/asynquence#115]
**[Editor's Note: This issue was transferred from the YDKJS repository, and is about `ASQ.iterable(..)`]**

```js
let steps=ASQ.iterable()
.then(function STEP1(token){
   let msg=token.messages[0];
   steps.then(function STEP3(msg){
      return msg+'STEP3';
   });

   return msg;
})
.then(function STEP2(msg){
   return msg+'STEP2';
});

ASQ("ASQ ")
.runner(steps)
.val(function(msg){
   console.log(msg);
});

console result: // **ASQ STEP2**
```

while I think it should be **ASQ STEP3**

I've made some tests and find the code in STEP3 will not run at all.

It seems the STEP3 is indeed added to the end of the queue at last. but won't be run.

Thanks for your help.

**Comment by getify** [comment]
As far as I recall, dynamically adding steps to an iterable-sequence instance during its iteration doesn't cause those steps to be recognized

However, the `runner(..)` plugin does support a way to dynamically add more "steps" to its run, by way of adding additional iterable sequences. Here's a [test from the contrib test-suite that shows using token.add(..)](https://github.com/getify/asynquence/blob/7d4c3c88aea87596526f72a8000e15e1aef37258/contrib/tests.js#L1546-L1570).

And here's a [codepen demo fixing your code](https://codepen.io/getify/pen/VweBLdK?editors=0011) to work as you asked:

```js
let steps = ASQ.iterable()
.then(function STEP1(token){
   let msg = token.messages[0];
   msg = msg + ' STEP1';
  
   // add another sequence of steps to the end of this run
   token.add(
      ASQ.iterable().then(function STEP3(msg){
         return msg + ' STEP3';
      })
   );

   return msg;
})
.then(function STEP2(msg){
   return msg + ' STEP2';
});

ASQ("ASQ")
.runner(steps)
.val(function(msg){
   console.log(msg);
});
// ASQ STEP1 STEP2 STEP3
```

**Comment by akixxx1982** [comment]
> As far as I recall, dynamically adding steps to an iterable-sequence instance during its iteration doesn't cause those steps to be recognized
> 
> However, the `runner(..)` plugin does support a way to dynamically add more "steps" to its run, by way of adding additional iterable sequences. Here's a [test from the contrib test-suite that shows using token.add(..)](https://github.com/getify/asynquence/blob/7d4c3c88aea87596526f72a8000e15e1aef37258/contrib/tests.js#L1546-L1570).
> 
> And here's a [codepen demo fixing your code](https://codepen.io/getify/pen/VweBLdK?editors=0011) to work as you asked:
> 
> ```js
> let steps = ASQ.iterable()
> .then(function STEP1(token){
>    let msg = token.messages[0];
>    msg = msg + ' STEP1';
>   
>    // add another sequence of steps to the end of this run
>    token.add(
>       ASQ.iterable().then(function STEP3(msg){
>          return msg + ' STEP3';
>       })
>    );
> 
>    return msg;
> })
> .then(function STEP2(msg){
>    return msg + ' STEP2';
> });
> 
> ASQ("ASQ")
> .runner(steps)
> .val(function(msg){
>    console.log(msg);
> });
> // ASQ STEP1 STEP2 STEP3
> ```

Thank you,I got it.

BTW,these is an example in your book ASYNC PERFORMANCE Appendix B   like below:


```js
var steps=ASQ.iterable();`

.then(function STEP1(token){
       var url=token.messages[0].url;
       if(token.messages[0].format){
             steps.then(token.messages[0].format);
        }

       return request(url);
})

.then(function STEP2(resp){
        if(/x1/.test(resp)){
                steps.then(function STEPS5(text){
                        return request(
                               "http://some.url.4/?v=" + text
                        );
               });
        }

        return ASQ().gate(
                 request("http://some.url.2/?v=" + resp,
                 request("http://some.url.3/?v=" + resp
         );
})

.then(function STEP3(r1,r2){ return r1+r2;});

var main=ASQ({
       url:"http://some.url.1",
       format:function STEP4(text){
              return text.toUpperCase();
       }
})
.runner(steps2)
.val(function(msg){
      console.log(msg);
});
```

Is that code work?Thanks again.

**Comment by getify** [comment]
No, I just tried it and that code doesn't work. The book is almost 5-1/2 years old. I don't recall if that approach did work at the time (it probably did because I assume I would have tested it), but to be honest, I don't even recall having written this example. And the documentation for the library doesn't document that capability. Shrugs. It's possible it may work in an older version of asynquence from 5+ years ago.

What's clear is asynquence definitely doesn't currently support extending sequences the way that example is depicting, but it should support it in the way I've suggested above.

**Comment by akixxx1982** [comment]
> No, I just tried it and that code doesn't work. The book is almost 5-1/2 years old. I don't recall if that approach did work at the time (it probably did because I assume I would have tested it), but to be honest, I don't even recall having written this example. And the documentation for the library doesn't document that capability. Shrugs. It's possible it may work in an older version of asynquence from 5+ years ago.
> 
> What's clear is asynquence definitely doesn't currently support extending sequences the way that example is depicting, but it should support it in the way I've suggested above.

OK!TKS for your reply,that made everything clear.
