### ISSUE TITLE
[thread moved]: asynquence error handling and API pros/cons

### ISSUE THREAD

**Issue by getify** [getify/asynquence#41]
[Editor: I have moved [part of a thread from another repo](https://github.com/getify/native-promise-only/issues/23), started by @benjamingr, here since it deals directly with asynquence]

> Consider this:
> 
> myService().then(function(){
>     doSomething(); // may throw an error, e.g. `JSON.parse`
> });
> 
> Most promise libraries include a way to debug promise based code without having to > always add a .catch(function(e){ throw e}) handler, some examples:
> - Native promises in Firefox use garbage collection in order to track unhandled rejections > and log the errors to the console.
> - Libraries like Q use .done to signal that a chain is terminated and rejections that got to that point log.
> - Bluebird promises track unhandled rejection approximately (in a way that practically always works).

**Comment by RezaErfani67** [comment]
asynquence is excellent library...
i cant work without it...
God Bless You Mr Kyle Simpson
