### ISSUE TITLE
Change main script in package.json to asq.src.js

### ISSUE THREAD

**Issue by tomjnsn** [getify/asynquence#63]
Don't know what the motivation is for using the uglified asq.js file as the main script in the package.json but doesn't help when trying to trace through errors :)  Any chance it could be switched to the uncompressed asq.src.js so node uses that instead?

**Comment by getify** [comment]
I wouldn't mind making the change, but I'm not entirely sure if it's future proof.

What if in the future I rewrite the source code to use ES6/ES7 features that not all node installations can support? In that case, the "uglified" (aka compiled) version of the code would have transpiled code and you'd need to be running that to ensure as much node support as possible.

Do you have any thoughts on that?

Is your concern debuggability? Would a sourcemap help (have considered adding that too)? Does the node process/debugger use sourcemaps?

**Comment by tomjnsn** [comment]
As far as I know node does not support sourcemaps without a module being added.

Regarding future proof, it's probably less of a big deal on the server side because you can just say: "this library requires nodejs 0.12.x or newer" and you'll have ES6 support, and same goes with ES7.  Not like trying to deal with all the different possible browsers that users might have in the wild.  I guess you could potentially run into problems with ES7 support if you rewrite it to work with that before node supports it though.

My concern is debuggability, I was trying to pass in an array of partial functions to .gate() and it was blowing up but I couldn't see what was going on (until I switched to the source file and saw that it doesn't take an array as an argument so I ended up with `asq.gate.apply(asq, arrayOfFunctions);` as a fix.  I can see that your docs don't say anything about passing in an array, and the examples have functions passed in as individual arguments, but it seemed intuitive to take an array of partial functions so I was trying that.

BTW, thanks for your article series on promises, best exploration and explanation I've read on them!

**Comment by getify** [comment]
If you'd like to submit a PR changing the package.json's `main` key to point to "asq.src.js" (and bumping the version to 0.6) i'd happily accept it. ;-)
