### ISSUE TITLE
Would like to catch errors inside a generator executed through runner()

### ISSUE THREAD

**Issue by zwegner** [getify/asynquence#79]
Not sure if this is expected behavior, or I'm just doing something incorrectly, but throwing an error in a wrapped function doesn't work like I would think--the first time an exception is thrown, it can be caught normally, but it disrupts the execution of the generator, so that the next time a value is yielded, execution never resumes after it. This is probably best illustrated with an example:

```js
var ASQ = require('asynquence-contrib');
function thrower(cb) {
    console.log('about to throw');
    throw "exc";
    cb();
}
function nonthrower(cb) {
    console.log('not throwing');
    cb();
}
ASQ().runner(function *(token) {
    try { yield ASQ.wrap(thrower)(); } catch (err) { }
    yield ASQ.wrap(nonthrower)();
    // Execution never returns here, though nonthrower() is called once
    yield ASQ.wrap(nonthrower)();
    return 0;
}).or(function(e) { console.error(e); }).val(function(v) { console.log(v); });
```
This would be useful to deal with functions like fs.stat, which throw an exception when a file doesn't exist--right now the only way to handle this is to either wrap fs.stat in its own function with a try/catch block, or split the generator in two with a .or() in between.

**Comment by zwegner** [comment]
Slight correction--fs.stat isn't throwing an exception, but passing a non-null error to the callback, that then gets handled in the normal way by runner(). So that probably isn't the best example...

**Comment by getify** [comment]
Sorry for taking so long to triage this particular issue. It turns out this is most likely a bug in `runner(..)`. It appears what's happening is that even though it seems to "recover" from the error thrown by `thrower()` so that you're able to `catch` it in the generator, something in the plumbing of `runner(..)` doesn't get reset so it just gives up and doesn't keep going after the next step. Will try to fix ASAP.

**Comment by getify** [comment]
Bug fixed. Embarrassingly big bug TBH. Your code should now work as you expected. Sorry for not finding and fixing this sooner. :/

**Comment by zwegner** [comment]
Awesome, thanks! This wasn't too hard to work around, but this bug fix should help clean up code on my side. Thanks for the great library too BTW!
