### ISSUE TITLE
Confused about .or()

### ISSUE THREAD

**Issue by richb-hanover** [getify/asynquence#81]
ASQ is very cool stuff. I am new to it, and was playing with an expanded copy of the first example in Part 1 of the davidwalsh.name blog (https://davidwalsh.name/asynquence-part-1).

If I throw an exception in a .then() block, all is well - .or() handles it. But if I throw an exception in the callback of the .then(), the .or() handler never gets called. 

**Example:** Here's a [jsfiddle](https://jsfiddle.net/richbhanover/y34j8k0j/) that shows my tests:

- If I uncomment the first throw statement (in Step 3b), all is fine.
- If I uncomment the second (inside the setTimeout() callback), the exception is not caught. Neither step4() nor the .or() get called.

In my read of the site, the post on David Walsh's site, and the Book (I bought it - thanks!) I understood that .or() would be able to catch all the errors. What have I misunderstood? How can I protect my code?

**Update:** s/.on()/.or()/g I also updated the [jsfiddle](https://jsfiddle.net/richbhanover/y34j8k0j/) to include a try/catch in the setTimeout() callback. It can call done.fail() to signal an error to the .or(..) handler. Solved!

**Comment by getify** [comment]
You keep saying `.on(..)`, but do you mean `.or(..)`? ASQ doesn't have a `.on(..)`.

**Comment by getify** [comment]
As to the substance of your question... a `throw` inside of an asynchronous callback are not able to be caught synchronously -- not even possible -- so ASQ cannot capture it. IOW, ASQ only knows about exceptions that actually bubble into it.

**Note:** the async-thrown exception in question doesn't go away, it just gets thrown to the global context, which in browsers can be trapped via [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) and in node can be trapped with [`process.on("uncaughtException")`](https://nodejs.org/api/process.html#process_event_uncaughtexception)

**Comment by richb-hanover** [comment]
re: .or() D'oh! 

re: exceptions inside async callback. I can wrap my async callback in try/catch, and that will, of course handle the error. 

But it sounds as if there's no way to get word back to the sequence from async-callback-land that something bad has happened... Is that correct? Thanks again.

**Comment by getify** [comment]
> there's no way to get word back to the sequence from async-callback-land

Not automatically, no, or ASQ would already be doing so. Of course, you can do the `try..catch` thing yourself and wire it to `done.fail(..)`:

```js
// ...
function step3b(done, msg) {
   console.log("Called step3b()");
   throw "step3b() got grumpy";
   setTimeout(function () {
      console.log("...completed step3b()");

      try {
         throw "step3b() got grumpy";
         done(msg + " Everyone ");
      }
      catch (err) {
         done.fail(err);
      }
   }, 3000);
}
// ...
```

**Comment by richb-hanover** [comment]
Excellent! That solves the question. I have updated the [jsfiddle](https://jsfiddle.net/richbhanover/y34j8k0j/) so that it includes a try/catch for step3b. 

(I also notice that step3a mentions done.fail(..), but didn't put two and two together...) Thanks!

**Comment by getify** [comment]
Cheers!
