### ISSUE TITLE
Recommended testing/assert library for code using sequences?

### ISSUE THREAD

**Issue by richb-hanover** [getify/asynquence#83]
I see you've hand crafted a considerable number of test cases in the repo (tests.js)

Do you have a recommended library/assert package(s) for testing sequences written using asynquence?

**Comment by getify** [comment]
Typically people cite preferrd libs like Mocha+Chai for async promise-style testing. It should be pretty easy to adapt sequences to promise-style testing, since you can always vend a real promise from a sequence using `toPromise()`. :)

**Comment by richb-hanover** [comment]
I will take a look at Chai as Promised - http://chaijs.com/plugins/chai-as-promised Thanks!
