### ISSUE TITLE
Combining Sequences (was: "interlocking sequences")

### ISSUE THREAD

**Issue by richb-hanover** [getify/asynquence#84]
I have an application that manages a TCP connection. I have the pieces mostly working, but I'm looking for a tidy way to make it bulletproof. I'm using two asynquence sequences:

- Sequence#1 establishes the connection, and sets up some overhead state between the two entities on either end of the connection

- Sequence#2 sends a command and waits for a response. 

So far, so good. 

But the connection can fail at any time. If there's no traffic required between the ends (that is, no calls of Sequence#2), then it's OK for the connection to be down for a long time.

I would like Sequence#2 simply to send its command if it detects that the connection is up. But if the connection's not up, I want Sequence#2 to invoke Sequence#1, then continue on its way after things have been re-established. 

What's the best way to express this conditional logic (invoke/don't invoke a separate sequence)? Thanks.

**Comment by richb-hanover** [comment]
I decided to whittle down my code example to make it more concrete. It's at: http://pastebin.com/H6wSV0d8 I have two sequences, both of which currently work on their own:

- Sequence#1 is called "Connect()" and it has multiple async .then() steps that establish a network connection.
- Sequence#2 is called SendCommand(), and it sends a command and waits for an event for its completion.

I would like to combine them so that SendCommand() optionally invokes Connect() if the connection's not already established. Let's assume that it can use a predicate "isConnected" that gives the state of the current connection.

My question is about syntax, more than anything else. I tried various combinations of .then() and .seq(), with various return values from Connect() (returning a sequence, calling done(), etc), but I'm still confused. 

- When it's necessary to call Connect() from SendCommand(), how should that be done - with .then(), .seq(), something else?
- How should Connect() be defined? What are its parameters? What should it return?
- Where should the test for isConnected occur? In Connect()? In SendCommand()?

Many thanks.

**Comment by richb-hanover** [comment]
Update - see http://pastebin.com/H6wSV0d8 for skeleton code that mimics real working code. 

The missing piece of my understanding was that sequences can be nested by passing in a "done" trigger, and having the (sub)sequence call that trigger when it has completed. In the case of the Connect() function, the first step of its sequence tests whether the connection has been established already or not.

- If it is connected, it calls the done trigger that was passed in to Connect().
- If it is not connected, it calls the step's done trigger, which then moves to the next step of the sequence to begin establishing the connection, etc.

**Comment by getify** [comment]
sorry i haven't gotten around to looking at your code yet. busy with lots of balls juggling.

one quick note: if you have one sequence that you want to wire into another sequence, like merging two into one, there's a variety of ways to do that... for example:

```js
var seq1 = goDoSomething1();
var seq2 = goDoSomething2();

// option 1
seq1
.seq(seq2)  // <-- note `seq(..)` here
.then(..)

// option 2
seq1.seq(function(){    // <-- note `seq(..)` here
   return seq2;
});

// option 3
seq1.then(function(done){   // <-- note `then(..)` here
   seq2.pipe(done);   // <-- note `pipe(..)` here
});

// option 4
seq1.then(function(done1){
   seq2.then(function(done2){
      done1();
      done2();
   });
});
```

I am not sure if that helps sort anything out for you, but maybe it gives some things to think about. I will try to get back here at some point to more closely think about your code examples.

**Comment by getify** [comment]
Closing for now. Reopen if more info is needed.
