### ISSUE TITLE
Babel 6: missing ) after argument list (asq.src.js line 66)

### ISSUE THREAD

**Issue by AlphaDork** [getify/asynquence#85]
This appeared after I updated Babel the the latest version. ;(  

"babel-core": "^6.5.1",
"babel-loader": "^6.2.2",
"babel-preset-es2015": "^6.5.0",
"babel-preset-react": "^6.5.0",
"babel-preset-stage-0": "^6.5.0",
 Asynquence version: 0.8.2

Error appears in Chrome console: 'Uncaught SyntaxError: missing ) after argument list'

The javascript it's complaining about transpiled:

function tapSequence(def) {
			// temporary `trigger` which, if called before being replaced
			// above, creates replacement proxy sequence with the
			// success/error message(s) pre-injected
			function trigger() {
ERROR---->	def.seq = createSequence.apply(Ã¸,arguments).defer();
			}

which corresponds to the original source in asq.src.js (0.8.2) line 66 ---

function tapSequence(def) {
		// temporary `trigger` which, if called before being replaced
		// above, creates replacement proxy sequence with the
		// success/error message(s) pre-injected
		function trigger() {
ORIG ---->def.seq = createSequence.apply(ø,arguments).defer();
		}

Clearly it has transpiled the 'ø' into 'Ã¸'.

This occurs EVERYWHERE the 'ø' character exists in the source. It errors on this code because this happened to be in that particular call chain.

This seems like a Babel bug to me - perhaps I'm not sending Babel a flag to transpile unicode correctly?

My JS loader in webpack looks thusly:
           {
                test: /\.jsx?$/,
                include: path.join(__dirname, 'src'),
                loaders: ['react-hot', 'babel']
           },

Which is pretty vanilla. 

Note that Webpack builds successfully - the error occurs when the browser tries to execute this function.

**Workaround:** Global search and replace 'ø' with 'nullObj' in Asynquence module.

**Comment by AlphaDork** [comment]
Also I realized that 'react-hot' may have been the issue. Removing it and leaving 'babel' as the only loader for jsx? files - the issue persists. So it does look like Babel is the culprit.

**Comment by loganfsmyth** [comment]
Saw @getify's tweet, so I figured I'd help since Sebastian has plenty to do. `Ã` is what you get when you decode `ø` as Latin1 instead of UTF8. If you look in the bundle on-disk, do you still see `Ã`? Wondering if perhaps you are serving your webpack bundle with the wrong encoding?

I don't know of any recent changed in Babel that might have introduced a code-generation issue, though I can't specifically discount it. Running the file through the Babel CLI returns the `ø` properly from what I can see.

**Comment by AlphaDork** [comment]
Exactly - it encodes as two chars 'Ã.' - my presets are es2015,stage-0, and react. Is there a way I can specify a the proper encoding in Babel? I've been looking but haven't found anything yet...

**Comment by AlphaDork** [comment]
It looks like it's a webpack issue -- https://github.com/webpack/webpack/issues/859 - this issue has been around for a while. Fortunately the workaround is simple. LOL!

**Comment by AlphaDork** [comment]
The root of the issue is Windows-7. It has set the encoding on the files in all node packages as Windows-1252. Brilliant. This clearly isn't a bug in any of the packages per se, just a feature of the OS.

**Comment by AlphaDork** [comment]
I am closing this because it's a just a cautionary tale more than a bug. Thank you for your patience!
