### ISSUE TITLE
Continue onerror fail

### ISSUE THREAD

**Issue by mahlu** [getify/asynquence#88]
How can I continue the sequence if one step error executing the next one?
I am getting:
 throw (sequence_errors.length === 1 ? sequence_errors[0] : sequence_errors);

I also tried with .pThen

**Comment by legodude17** [comment]
Do you want to just ignore sequence errors? It is not very clear. If you want to ignore them you want to use `.defer()`.
`var seq = ASQ(...).defer()`

**Comment by getify** [comment]
An errored sequence cannot be continued (reset to success), unless you use, as you indicated, the pthen/pcatch methods. If you tried that and it didn't work, please post a specific question with what code is failing for you.
