### ISSUE TITLE
[question] why do u use setImmediate not process.nextTick ?

### ISSUE THREAD

**Issue by muxahuk** [getify/asynquence#89]
Hello, i wonder what is behind these choice ? why do u use setImmediate not process.nextTick ?

**Comment by legodude17** [comment]
I think it is because setImmediate is closer to setTimeout than prcoess.nextTick. That is only speculation.

**Comment by getify** [comment]
I didn't find value in picking different scheduling mechanisms between node and the browser.

**Comment by legodude17** [comment]
Then why don't you use setTimeout in node and browser?

**Comment by getify** [comment]
because setImmediate performs better in IE/edge than setTimeout(0)...and back then I was really hoping/betting that other browsers would land setImmediate eventually.
