### ISSUE TITLE
ASQ.iterable() is not a function...

### ISSUE THREAD

**Issue by AlphaDork** [getify/asynquence#98]
I am using version ^0.9.0 of asynquence (latest and greatest!) 

I  get the following error with the simple code below:

**Uncaught TypeError: _asynquence2.default.iterable is not a function(…)**

``import ASQ from 'asynquence';

var isq = ASQ.iterable()
     .then(function(){ return 5; })
    .then(function(){ return 10; })
    .then(function(){ return 15; });

    console.log(isq.next().value);    // 5
    console.log(isq.next().value);    // 10
    console.log(isq.next().value);    // 15
``

I'm usually so good with sample code - am I missing something or is it really broken?

**Comment by getify** [comment]
iterable is a plugin and requires the contrib package to define it. btw, untested if this kind of thing works in es6 modules.

**Comment by AlphaDork** [comment]
the dreaded require... LOL. It's not real happy with ES6 anyhow. :) 
Thanks!

**Comment by jabidof** [comment]
@AlphaDork @getify Can you confirm the `asynquence-contrib` version of ASQ can't be used with ES6?
Thanks for your feedback.
J.

**Comment by nilsriga** [comment]
I'm getting the same error
So what am I doing wrong?
nor import ASQ nor requrie('asynquence-contrib") works.
So the contrib plugins don't work for nodejs?

**Comment by getify** [comment]
@snotrman asq and contrib definitely work in node. however, they're not ES modules so you should require() them.
