### ISSUE TITLE
ES6 asynquence-contrib importing issue

### ISSUE THREAD

**Issue by jabidof** [getify/asynquence#99]
Hello,
First of all thanks for the very nice books and library you've written. 
I started using ASQ like this in my ReactJS SPA:
```
import React, { Component } from 'react';
// HTTP requests
import axios from 'axios';
// Sequences
import ASQ from 'asynquence';
...
```
That works nicely, and I can already take advantage of RFP in my multiple API request (using Axios).

However, I'd like to go ahead with functions like .map, etc. coming from the asynquence-contrib. I thus changed my code to:
```
import React, { Component } from 'react';
// HTTP requests
import axios from 'axios';
// Sequences
import ASQ from 'asynquence-contrib';
```
There we go with many errors/warnings from WEBPACK.

> freshy -> managed and installed
> ERROR in ./~/resolve/lib/async.js
> Module not found: Error: Cannot resolve module 'fs' in... -> I managed adding a:
> 	node: {
> 		fs: 'empty'
> 	},
> in my config file -> solved.

My problem is all those warning messages like:

> WARNING in ./~/freshy/README.md
> Module parse failed: ....../node_modules/freshy/README.md Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type.
> 

I have many of them. I understand that webpack tries to parse all file from the freshy or asynquence-contrib folders and I could prevent webpack from doing so.
But I'm a bit lost in the way to use ASQ with its contribs in the ES6 way of importing modules.

Thanks for any hint you could bring in.

J.

**Comment by legodude17** [comment]
You will probably want to just run `contrib/bundle.js` before you try to build it with webpack.

**Comment by jabidof** [comment]
Hi @legodude17 
Sorry for my late answer. I actually did this I guess from the beginning. To be more precise, here is the steps I took:
Within my application folder
1. npm install --save asynquence
2. npm install --save asynquence-contrib
Within the node_modules/asynquence-contrib folder, I launched "npm run build". Then in my code
```
import React, { Component } from 'react';
// HTTP requests
import axios from 'axios';
// Sequences
import ASQ from 'asynquence-contrib';
```
However, I still have all sorts of warnings, etc. and can't use the add-ons features like Map, Race, etc.

Can someone point me to some references to read?

Thanks
J.

**Comment by legodude17** [comment]
I think that what you would want to do is to is:
1. `npm install asynquence -S`
2. In `node_modules/asynquence/contrib` folder, `npm run build`

```js
inport ASQ from 'asynquence/conrtib'

**Comment by RezaErfani67** [comment]
@legodude17 
what the meaning of {-S} in 
npm install asynquence -S  
?

**Comment by dmccarrick** [comment]
Hi,

I'm having issues importing the runner plugin within a browser based application. Not using node or anything like that. I've included contrib-wrapper.js alongside the main asq.src.js file. ASQ is accessible, however I get an error:

plugin.runner.js?av=1565788497:11 Uncaught ReferenceError: ARRAY_SLICE is not defined

I can see where ARRAY_SLICE is declared within contrib-wrapper.js, but runner seems unable to use it. Any advice?

**Comment by getify** [comment]
It seems like you're also including `plugin.runner.js` which you shouldn't be. That file gets built into the contrib bundle when you run the build.

**Comment by dmccarrick** [comment]
Ah Ok, thanks That helps. Is there a guide, anywhere, describing how to set this up for the browser? The readme suggests it's a simpler process than it is. Thanks

**Comment by getify** [comment]
Did you find this section? https://github.com/getify/asynquence/blob/master/contrib/README.md#building-contrib-bundle

**Comment by dmccarrick** [comment]
Cool, that's great. Thanks for your help!
